#.travis.yml
sudo: required

language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools

script:
  - ng build --prod --aot

deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  message: "automated deploy from travis"